### ISSUE TITLE
강연자 신청화면 STEP02 영역 오류

### ISSUE THREAD

**Issue by comeannn** [somul-project/somul-system-frontend#102]
<img width="1680" alt="스크린샷 2020-05-26 오전 2 56 53" src="https://user-images.githubusercontent.com/61775903/82834586-90697900-9efc-11ea-82f6-45e36ca3e818.png">

STEP02의 왼쪽 영역이 전체 사이즈보다 작게 구현됩니다.

**Comment by cos18** [comment]
#78 과 중복된 이슈입니다!
