### ISSUE TITLE
Select 컴포넌트에 버튼 3개짜리 추가하기

### ISSUE THREAD

**Issue by dsa28s** [somul-project/somul-system-frontend#15]
Select 컴포넌트가 변경됐어요!
기존거에서 3개짜리 버튼이 추가됐습니다ㅠㅠ

Design Guide Web 6 를 참조하시면 될거같아요!

**Comment by cos18** [comment]
이전 Select 컴포넌트를 만들 당시(#3) 3개의 버튼도 수용할수 있도록 구현해 놓았습니다.
[스토리북에도](https://github.com/somul-project/somul-system-frontend/blob/master/src/frameworks/web/components/atoms/Select/Select.stories.tsx) 버튼 3개짜리를 구현해놓았습니다.

추가적으로 구현해야할 사항이 있나요?

**Comment by cos18** [comment]
@dsa28s 확인 부탁드립니다 🙏

**Comment by dsa28s** [comment]
앗, 이미 구현되어 있었군요ㅠㅠ 디자인 시안에는 없어서 구현이 안된줄 알았습니다!!
감사합니당!!
