### ISSUE TITLE
Label에 isHighlighted 옵션 추가

### ISSUE THREAD

**Issue by cos18** [somul-project/somul-system-frontend#20]
#1 에 추가된 Label 컴포넌트에 bool 옵션인 isHighlighted를 추가해 텍스트 뒤에 형광팬이 칠해진 것 처럼 밑줄이 그어져있는 모양을 만들어야합니다. 추후 랜딩페이지에 쓰이는 옵션이니 빠르게 진행할 예정입니다.

**Comment by harrydrippin** [comment]
`isHighlighted` 가 옳은 것 같습니다!

**Comment by cos18** [comment]
> `isHighlighted` 가 옳은 것 같습니다!

수정했습니다! 이젠 영어를 다시 배워야할거 같네요 😓
