### ISSUE TITLE
로그인 되어 있을 경우, 헤더에 사용자 프로필 화면 표시 로직 추가 (비즈니스 로직 제외)

### ISSUE THREAD

**Issue by dsa28s** [somul-project/somul-system-frontend#34]
사용자 프로필을 구성하는 컴포넌트
![Screen Shot 2020-05-07 at 12 44 41 AM](https://user-images.githubusercontent.com/10934461/81198015-f3ea4000-8ffb-11ea-906b-ab76110d654c.png)
는 각각 구현되어 있으나, 실제 컴포넌트가 헤더바에 연결되지 않았습니다.

로그인 되었을 때, 안되어 있을 때 분기를 해서 적당한 디자인을 보여줘야 합니다.

**Comment by cos18** [comment]
#53 에서 진행중인 이슈입니다.
